baseURL: "https://elialombardi.github.io/lauragrosso/"
languageCode: "en-us"
title: "Laura Grosso Test"
theme: "mytheme"
enableRobotsTXT: true
publishdir: "./docs/"

module:
  mounts:
    source: "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target: "assets/js/bootstrap.bundle.min.js"

# minify:
#   disableXML: true
#   minifyOutput: true

# params:
#   defaultTheme: auto # dark, light
#   disableThemeToggle: false