baseURL: "https://elialombardi.github.io/lauragrosso/"
languageCode: "en-us"
title: "Laura Grosso Test"
theme: "PaperMod"
enableRobotsTXT: true
publishdir: "./docs/"

minify:
  disableXML: true
  minifyOutput: true

params:
  defaultTheme: auto # dark, light
  disableThemeToggle: false