baseURL: "https://lauragrosso.com"
languageCode: "en-us"
title: "Laura Grosso"
enableRobotsTXT: true
publishdir: "./docs/"
params:
  description: "Arte della Pittura"

menu:
  main:
    - name: Roma
      url: /galleries/roma
      weight: -130

    - name: Umani
      url: /galleries/umani
      weight: -129
    - name: Persone
      url: /galleries/persone
      weight: -128

    - name: Nature Morte
      url: /galleries/nature-morte
      weight: -127

    - name: Blog
      url: /blog
      weight: -120
      params:
        showHomepage: true
        
    - name: CV
      url: /cv
      weight: -110
      params:
        showHomepage: true


    - name: Archivio
      url: /galleries/archivio
      weight: -100
      params:
        showHomepage: true
# minify:
#   disableXML: true
#   minifyOutput: true

# params:
#   defaultTheme: auto # dark, light
#   disableThemeToggle: false
